version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: kauth
    main: ./cmd/kauth
    binary: kauth
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/krezh/kauth/cmd/kauth/cmd.Version={{.Version}}
      - -X github.com/krezh/kauth/cmd/kauth/cmd.GitCommit={{.FullCommit}}

  - id: kauth-server
    main: ./cmd/kauth-server
    binary: kauth-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/krezh/kauth/cmd/kauth/cmd.Version={{.Version}}
      - -X github.com/krezh/kauth/cmd/kauth/cmd.GitCommit={{.FullCommit}}

dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}-server:{{ .Version }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}-server:latest"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^chore"
      - "^ci"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  prerelease: auto
  mode: append
  footer: |
    ## Container Images

    ```bash
    docker pull ghcr.io/{{ .Env.GITHUB_REPOSITORY }}-server:{{ .Version }}
    docker pull ghcr.io/{{ .Env.GITHUB_REPOSITORY }}-server:latest
    ```
