apiVersion: v1
kind: Namespace
metadata:
  name: kauth
---
apiVersion: v1
kind: Secret
metadata:
  name: kauth-config
  namespace: kauth
type: Opaque
stringData:
  OIDC_ISSUER_URL: "https://authentik.example.com/application/o/kube-apiserver/"
  OIDC_CLIENT_ID: "kube-apiserver"
  OIDC_CLIENT_SECRET: "your-client-secret-here"
  CLUSTER_NAME: "kubernetes"
  # CLUSTER_SERVER: Auto-detected from in-cluster environment
  # CLUSTER_CA_DATA: Auto-detected from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  BASE_URL: "https://kauth.example.com"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kauth
  namespace: kauth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kauth
  template:
    metadata:
      labels:
        app: kauth
    spec:
      serviceAccountName: kauth
      containers:
      - name: kauth
        image: ghcr.io/yourusername/kauth-server:latest
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - secretRef:
            name: kauth-config
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kauth
  namespace: kauth
---
apiVersion: v1
kind: Service
metadata:
  name: kauth
  namespace: kauth
spec:
  selector:
    app: kauth
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kauth
  namespace: kauth
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - kauth.example.com
    secretName: kauth-tls
  rules:
  - host: kauth.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kauth
            port:
              number: 80
